name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: komandanto666514/cv-devops:latest

    - name: Deploy to server
      env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SERVER_IP << 'EOF'
            sudo docker pull komandanto666514/cv-devops:latest
            sudo docker stop cv-devops-container || true
            sudo docker rm cv-devops-container || true
            sudo docker run -d --name cv-devops-container -p 80:80 -p 443:443 komandanto666514/cv-devops:latest
  
            sudo docker exec -i cv-devops-container sh -c "mkdir -p /var/www/certbot /etc/letsencrypt/live/alexkomendantov.top /etc/letsencrypt/archive/alexkomendantov.top"
            sudo docker exec -i cv-devops-container sh -c "touch /etc/letsencrypt/options-ssl-nginx.conf /etc/letsencrypt/ssl-dhparams.pem"
            sudo docker exec -i cv-devops-container sh -c "chown -R root:root /var/www/certbot /etc/letsencrypt"
            sudo docker exec -i cv-devops-container sh -c "chmod -R 755 /var/www/certbot /etc/letsencrypt"
          EOF
